### ISSUE TITLE
Standalone mode

### ISSUE THREAD

**Issue by icetronics** [ajhsu/chromecast-device-emulator#1]
Hi @ajhsu,
Just found this, great initiative!
I tried get it going in standalone mode but 'npm start' fails with:
`Error: Cannot find module '...\chromecast-device-emulator\dist\example.js'`

Would you be able to help me how it can be started and also how I can load my own custom receiver app in it for testing?

Thanks a lot in advance!

**Comment by ajhsu** [comment]
Since you just opened up the first issue of this package, thanks for point that out.
And I have already fixed that! Please re-pull and try again.

Meanwhile, I feel sorry for the incomplete status of this pet-project on my own.
But I'll keep improving it, so any feedback is welcome! 😄

**Comment by icetronics** [comment]
Thanks, works fine now. Could you give any guide how to test a custom receiver app using your emulator?

**Comment by ajhsu** [comment]
Yeah, sure, I think it would be better to write a basic usage example into README file.
While it may takes few days to write, I would closing this issue and create another for it.

Thanks for your feedback!

**Comment by icetronics** [comment]
OK, sounds swell, thanks!
