### ISSUE TITLE
Adding basic usage example

### ISSUE THREAD

**Issue by ajhsu** [ajhsu/chromecast-device-emulator#2]
Writing some basic examples about how to get started with both as a standalone tool and as a node package.

Respond to #1

**Comment by icetronics** [comment]
I can offer proofreading, correction and testing the guide with a real app.

**Comment by ajhsu** [comment]
@icetronics Thanks for your support!

**Comment by ajhsu** [comment]
@icetronics My apologized for slow progression. I'm currently not working on a Chromecast project for months. But we planned to kick off the development of our Chromecast Project on Q1, 2018. That is, I will continue to make this happen at the time.

Meanwhile, I got some ideas about new features in upcoming versions, and any ideas or suggestion are welcomed as well.

Thanks for your patient.

**Comment by ajhsu** [comment]
Hi @icetronics 
Sorry for the long waiting,

I just updated the README file with basic usage in details; Please kindly take a look.
Meanwhile, I also wrote [a basic tutorial](https://github.com/ajhsu/chromecast-device-emulator/blob/master/docs/basic-receiver-caf.md) about how to integrate with your CAF receiver app as well.
