### ISSUE TITLE
how to get start?

### ISSUE THREAD

**Issue by thewayur** [ajhsu/chromecast-device-emulator#4]
i am web, android developer but no idea about node, CLI..
can you please guide me. a little will help me to explore by myself.

**Comment by ajhsu** [comment]
Hi @thewayur ,
May I know what you're going to do with the emulator? I believed I could give you a hint only if I know what's the problem you're trying to solve.
And I myself is using the emulator for testing Chromecast [receiver apps](https://developers.google.com/cast/docs/caf_receiver/) by the way.
